name: Run Scrapy Spider

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest

    services:
      splash:
        image: scrapinghub/splash
        options: --privileged --name splash -p 8050:8050

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scrapy Spider
        env:
          SPLASH_URL: http://localhost:8050
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          cd studentbostad_scraper/studentbostad_scraper/spiders
          scrapy crawl number_checker
